org.Admin/Controllers/ORGController.cs
using org.Admin.Controllers;
using org.Bll;
using org.Common;
using org.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace org.Admin.Controllers
{
    public class ORGController : BaseController
    {
        // GET: ORG
        public ActionResult Index(int p = 1)
        {
            if (_UserInfo.type != 1)
            {
                return Content("<script>alert('无权限访问！');location.href='/'</script>");
            }
            string sql = " where 1=1";
            string order = " order by oid asc";

            var plist = organizationBll.Page(p, _PageSize, sql, order);
            var pager = PagerUtils.PageList(_PageSize, p, (int)plist.TotalItems);
            ViewBag.Pager = pager;
            ViewBag.Items = plist.Items;
            ViewBag.LoginUser = _UserInfo;
            return View();
        }

        public ActionResult Edit(long id = 0)
        {
            if (id != 0)
            {
                var model = organizationBll.SingleOrDefault(id);
                return View(model);
            }
            ViewBag.LoginUser = _UserInfo;
            return View(new organization());
        }

        public ActionResult EditORG(organization model)
        {

            bool flag = true;
            if (string.IsNullOrEmpty(model.oname))
            {
                flag = false;
                Error("请填写组织名");
            }
            if (flag)
            {
                var info = organizationBll.SingleOrDefault($"where oname = '{model.oname}' limit 1");
                if (info != null && info.oid !=model.oid)
                {
                    Error("此组织名已注册：" + info.oname);

                }
                else
                {
                    if (model.oid == 0)
                    {
                        model.created = TypeConvert.DateTimeToInt(DateTime.Now);
                        model.status = (int)Enums.StatusEnum.Normal;
                        var u = organizationBll.AddBackId(model);
                        Success("添加成功!", Url.Action("Index"));
                    }
                    else {
                        var u = organizationBll.Update(model);
                        Success("修改成功!", Url.Action("Index"));
                    }

                }
            }
            return Content("");
        }

        public ActionResult Delete(long id)
        {
            if (_UserInfo.type != 1)
            {
                return Content("<script>alert('无权限访问！');location.href='/'</script>");
            }
            if (id == 1)
            {
                return Content("<script>ModelExt.alert('您删您妈拉个靶子呢删？！');location.href='/'</script>");
            }
            var s = organizationBll.Delete(id);
            if (s)
            {
                return NetJSON(1);
            }
            return NetJSON(0);
        }
    }
}

org.Admin/Controllers/RecordController.cs
using org.Bll;
using org.Common;
using org.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace org.Admin.Controllers
{
    public class RecordController : BaseController
    {
        // GET: Record
        public ActionResult Index(DateTime? date = null, int p = 1, string uname = "")
        {
            if (date == null)
                date = DateTime.Now;
            int week = (int)date.Value.DayOfWeek;
            if (week == 0)
                week = 7;
            DateTime timebegin = Convert.ToDateTime(date.Value.AddDays(-(week - 1)).ToString("yyyy-MM-dd 00:00"));
            DateTime timeend = Convert.ToDateTime(date.Value.AddDays(8 - week).ToString("yyyy-MM-dd 00:00"));
            long timebeginnumber = TypeConvert.DateTimeToLong(timebegin);
            long timeendnumber = TypeConvert.DateTimeToLong(timeend);
            string sql = " where 1=1 ";
            if (!string.IsNullOrEmpty(uname))
            {
                sql += " and uname like '%" + uname.TrimEnd() + "%'";
            }
            sql += string.Format(" and created between {0} and {1}", timebeginnumber, timeendnumber);
            sql += string.Format(" and oid = {0}", _UserInfo.oid);
            string order = " order by sumpoints asc";

            var plist = RecordBll.Page(p, _PageSize, sql, order);
            var pager = PagerUtils.PageList(_PageSize, p, (int)plist.TotalItems);
            ViewBag.Pager = pager;
            ViewBag.Items = plist.Items;
            ViewBag.LoginUser = _UserInfo;
            ViewBag.CurrentTime = date.Value.ToString("yyyy-MM-dd");
            return View();
        }

        public ActionResult Edit()
        {
            ViewBag.LoginUser = _UserInfo;
            DateTime date = DateTime.Now;
            int week = (int)date.DayOfWeek;
            if (week == 0)
                week = 7;
            DateTime timebegin = Convert.ToDateTime(date.AddDays(-(week - 1)).ToString("yyyy-MM-dd 00:00"));
            DateTime timeend = Convert.ToDateTime(date.AddDays(8 - week).ToString("yyyy-MM-dd 00:00"));
            long timebeginnumber = TypeConvert.DateTimeToLong(timebegin);
            long timeendnumber = TypeConvert.DateTimeToLong(timeend);
            string sql = string.Format(" where created between {0} and {1}", timebeginnumber, timeendnumber);
            sql += string.Format(" and uid = {0}", _UserInfo.uid);
            var model = RecordBll.SingleOrDefault(sql);
            if (model == null)
            {
                return View(new Record());
            }
            if (model.bagtype != (int)Enums.BagType.Normal)
            {
                return Content("<script>alert('该周礼包已分配，不能再修改！')</script>");
            }
            return View(model);

        }
        public ActionResult EditRecord(Record model)
        {
 
            long powernum = 0;
            if (model.powernum < 100000)
            {
                powernum = 1000;
            }
            else {
                powernum =Convert.ToInt64(1000 + Math.Floor((Convert.ToDecimal(model.powernum - 100000) / 20000)) * 200);
            }
            long tongling = model.tongling;
            long fighttimepoints = model.fighttime * 500;
            long lastweekdeduction = 0;
            {
                DateTime date = DateTime.Now.AddDays(-7);
                int week = (int)date.DayOfWeek;
                if (week == 0)
                    week = 7;
                DateTime timebegin = Convert.ToDateTime(date.AddDays(-(week - 1)).ToString("yyyy-MM-dd 00:00"));
                DateTime timeend = Convert.ToDateTime(date.AddDays(8 - week).ToString("yyyy-MM-dd 00:00"));
                long timebeginnumber = TypeConvert.DateTimeToLong(timebegin);
                long timeendnumber = TypeConvert.DateTimeToLong(timeend);
                string sql = string.Format(" where created between {0} and {1}", timebeginnumber, timeendnumber);
                sql += string.Format(" and uid = {0}", model.uid);
                var lastweekmodel = RecordBll.SingleOrDefault(sql);
                if (lastweekmodel != null)
                {
                    switch (lastweekmodel.bagtype)
                    {
                        case (int)Enums.BagType.CS: lastweekdeduction = -800; break;
                        case (int)Enums.BagType.YX: lastweekdeduction = -500; break;
                        case (int)Enums.BagType.JY: lastweekdeduction = -300; break;
                    }
                }
            }
            List<Reward> rewardlst = RewardBll.Fetch("where uid=" + _UserInfo.uid);
            long otherbonuspoints = 0;
            {
                otherbonuspoints = rewardlst.Where(x => x.type == (int)Enums.RewardType.reward).Sum(x => x.points);
            }
            long otherdeduction = 0;
            {
                otherdeduction = rewardlst.Where(x => x.type == (int)Enums.RewardType.punishment).Sum(x => x.points);

            }
            model.otherbonuspoints = otherbonuspoints;
            model.otherdeduction = otherdeduction;
            model.sumpoints = powernum + tongling + fighttimepoints + lastweekdeduction + otherbonuspoints + otherdeduction;
            model.bagtype = (int)Enums.BagType.Normal;
            if (model.rid == 0)
            {
                model.uid = _UserInfo.uid;
                model.uname = _UserInfo.uname;
                model.oid = _UserInfo.oid;
                model.oname = _UserInfo.oname;
                model.created = TypeConvert.DateTimeToLong(DateTime.Now);
                RecordBll.Add(model);

            }
            else {
                RecordBll.Update(model);
            }
            Success("保存成功!", Url.Action("Index"));
            return Content("");
        }

        public ActionResult Distribution(int cscount=0, int yxcount=0, int jycount=0)
        {
            DateTime date = DateTime.Now;
            int week = (int)date.DayOfWeek;
            if (week == 0)
                week = 7;
            DateTime timebegin = Convert.ToDateTime(date.AddDays(-(week - 1)).ToString("yyyy-MM-dd 00:00"));
            DateTime timeend = Convert.ToDateTime(date.AddDays(8 - week).ToString("yyyy-MM-dd 00:00"));
            long timebeginnumber = TypeConvert.DateTimeToLong(timebegin);
            long timeendnumber = TypeConvert.DateTimeToLong(timeend);
            string sql = string.Format(" where created between {0} and {1}", timebeginnumber, timeendnumber);
            sql += string.Format(" and oid = {0} order by sumpoints asc", _UserInfo.oid);
            List<Record> lst = RecordBll.Fetch(sql);
            if (lst.FirstOrDefault(x => x.bagtype > 0)!=null)
            {
                return Content("<script>alert('该周礼包已分配，不能再分配！')</script>");

            }
            foreach (var item in lst)
            {
                if (cscount > 0)
                {
                    item.bagtype = (int)Enums.BagType.CS;
                    RecordBll.Update(item);
                    cscount--;
                }
                else if (yxcount > 0)
                {
                    item.bagtype = (int)Enums.BagType.YX;
                    RecordBll.Update(item);
                    yxcount--;
                }
                else if (jycount > 0)
                {
                    item.bagtype = (int)Enums.BagType.JY;
                    RecordBll.Update(item);
                    jycount--;
                }
            }
            return NetJSON(new OutInfo() { code = 1, msg = "处理成功！" });
        }
    }
}

org.Admin/Controllers/RewardController.cs
using org.Bll;
using org.Common;
using org.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace org.Admin.Controllers
{
    public class RewardController : BaseController
    {
        // GET: Reward
        public ActionResult Index(int p = 1, string name = "")
        {
            string sql = " where 1=1";
            if (!string.IsNullOrEmpty(name))
            {
                sql += " and uname like '%" + name.TrimEnd() + "%'";
            }
            string order = " order by created desc";

            var plist = RewardBll.Page(p, _PageSize, sql, order);
            var pager = PagerUtils.PageList(_PageSize, p, (int)plist.TotalItems);
            ViewBag.Pager = pager;
            ViewBag.Items = plist.Items;
            ViewBag.UserInfo = _UserInfo;
            ViewBag.LoginUser = _UserInfo;
            return View();
        }
        public ActionResult Edit(long id = 0)
        {
            if (_UserInfo.type == 3)
            {
                return Content("<script>alert('无权限访问！');location.href='/'</script>");
            }
            if (id != 0)
            {
                var model = RewardBll.SingleOrDefault(id);
                return View(model);
            }
            ViewBag.LoginUser = _UserInfo;
            return View(new Reward());
        }

        public ActionResult EditReward(Reward model)
        {
            if (_UserInfo.type == 3)
            {
                return Content("<script>alert('无权限访问！');location.href='/'</script>");
            }
            bool flag = true;
            if (model.uid <= 0)
            {
                flag = false;
                Error("请选择用户");
            }
            if (model.type <= 0)
            {
                flag = false;
                Error("请选择奖惩类型");
            }
            if (flag)
            {

                if (model.id == 0)
                {
                    model.created = TypeConvert.DateTimeToInt(DateTime.Now);
                    var u = RewardBll.AddBackId(model);
                    Success("添加成功!", Url.Action("Index"));
                }


            }
            return Content("");
        }


        public ActionResult Delete(long id)
        {
            if (_UserInfo.type == 3)
            {
                return Content("<script>alert('无权限访问！');location.href='/'</script>");
            }
            var s = RewardBll.Del(id);
            if (s)
            {
                return NetJSON(1);
            }
            return NetJSON(0);
        }
    }
}

org.Admin/Controllers/UserController.cs
using org.Bll;
using org.Common;
using org.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace org.Admin.Controllers
{
    public class UserController : BaseController
    {
        // GET: User
        public ActionResult Index(int p = 1,string name="")
        {
            string sql = " where 1=1 and user_type !=1";
            if (!string.IsNullOrEmpty(name))
            {
                sql += " and uname like '%"+name.TrimEnd()+"%'";
            }
            string order = " order by uid asc";

            var plist = UserBll.Page(p, _PageSize, sql, order);
            var pager = PagerUtils.PageList(_PageSize, p, (int)plist.TotalItems);
            ViewBag.Pager = pager;
            ViewBag.Items = plist.Items;
            ViewBag.UserInfo = _UserInfo;
            ViewBag.LoginUser = _UserInfo;
            return View();
        }

        public ActionResult Edit(long id = 0)
        {
            if (_UserInfo.type == 3)
            {
                return Content("<script>alert('无权限访问！');location.href='/'</script>");
            }
            if (id != 0)
            {
                var model = UserBll.SingleOrDefault(id);
                return View(model);
            }
            ViewBag.LoginUser = _UserInfo;
            return View(new User());
        }

        public ActionResult EditUser(User model)
        {
            if (_UserInfo.type == 2)
            {
                return Content("<script>alert('无权限访问！');location.href='/'</script>");
            }
            bool flag = true;
            if (string.IsNullOrEmpty(model.uname))
            {
                flag = false;
                Error("请填写前台用户名");
            }
            if (string.IsNullOrEmpty(model.QQnumber.ToString()))
            {
                flag = false;
                Error("请填写QQ账号");
            }
            if (string.IsNullOrEmpty(model.password.ToString()))
            {
                flag = false;
                Error("请填写密码");
            }
            if (model.oid<=0)
            {
                flag = false;
                Error("请选择组织");
            }
            if (model.user_type <= 0)
            {
                flag = false;
                Error("请选择角色");
            }
            if (flag)
            {
                var info = UserBll.SingleOrDefault($"where QQnumber = '{model.QQnumber}' and oid={model.oid}  limit 1");
                if (info != null && info.uid !=model.uid)
                {
                    Error("此成员已注册：" + info.uname);

                }
                else
                {
                    if (model.uid == 0)
                    {
                        model.created = TypeConvert.DateTimeToInt(DateTime.Now);
                        model.status = (int)Enums.StatusEnum.Normal;
                        model.password = Utils.MD5(model.password);
                        var u = UserBll.AddBackId(model);
                        Success("添加成功!", Url.Action("Index"));
                    }
                    else
                    {
                        var u = UserBll.Update(model);
                        Success("修改成功!", Url.Action("Index"));
                    }

                }
            }
            return Content("");
        }

        public ActionResult Delete(long id)
        {
            if (_UserInfo.type == 3)
            {
                return Content("<script>alert('无权限访问！');location.href='/'</script>");
            }
            var s = UserBll.Delete(id);
            if (s)
            {
                return NetJSON(1);
            }
            return NetJSON(0);
        }

        public ActionResult GetUserList(string name)
        {
            List<User> list = new List<User>();
            if (!string.IsNullOrEmpty(name))
            {
                list = UserBll.Fetch($"where uname like '%{name}%'");
            }
            return NetJSON(list);

        }
    }
}

org.Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@Page.Title</title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <meta content="telephone=no" name="format-detection" />
    <script type="text/javascript" src="/static/js/jquery.min.js"></script>
    <script type="text/javascript" src="~/Static/js/lodash.js"></script>
    <script type="text/javascript" src="/static/js/semantic.min.js"></script>
    <script type="text/javascript" src="~/Static/js/semanticModelEXT.js"></script>
    <script type="text/javascript" src="/static/js/docs.js"></script>
    <script type="text/javascript" src="/static/js/admin.js?20180503"></script>
    @RenderSection("js", required: false)
    <link rel="stylesheet" type="text/css" class="ui" href="/static/css/semantic.min.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/docs.css?v=20180502v2" />
    <link rel="stylesheet" type="text/css" href="/static/css/admin.css?v=20180502v2" />
    @RenderSection("css", required: false)
    <script type="text/javascript">
        $(function () {
            @Html.Raw(ViewBag.Js)
        });
    </script>
</head>
<body id="example" class="wide">
    <!--mobile时的菜单-->
    <div class="ui vertical inverted sidebar menu" id="toc">
        @Html.Partial("_Menu")
    </div>
    <div class="ui black big launch right attached fixed button">
        <i class="content icon"></i>
        <span class="text">Menu</span>
    </div>
    <!--mobiel时的头部-->
    <div class="ui fixed inverted main menu">
        <div class="ui container">
            <a class="launch icon item">
                <i class="content icon"></i>
            </a>
            <div class="item">
                @(Page.Title)
            </div>
        </div>
    </div>
    <div class="pusher">
        <div class="full height">
            <div class="toc">
                <!--pc的菜单-->
                <div class="ui vertical inverted sticky menu" id="pc">
                    @Html.Partial("_Menu")
                </div>
            </div>
            <script type="text/javascript">
                var url = window.location.pathname;
                var menus = $(".leftMenu .menu .item");
                for (var i = 0; i < menus.length; i++) {
                    if (menus[i].pathname == url) {
                        menus.eq(i).parents('.item').addClass("active");
                        menus[i].style.color = "#fff";
                        menus[i].style.textDecoration = "underline";
                    }
                }
                $('.leftMenu .item').click(function () {
                    $(".leftMenu .item").removeClass("active");
                    $(this).addClass("active");
                })
            </script>
            @RenderBody()
        </div>
        @RenderSection("script", required: false)

</body>
</html>

org.Admin/Views/Shared/_Menu.cshtml
@using org.Common;
@using org.Model;
@{

    LoginUser UserInfo = ViewBag.LoginUser;
}

<div class="item">
    <a class="ui logo icon image" href="/">
        <img src="/static/images/logo.png">
    </a>
    <a href="/"><b>全村的希望</b></a>
</div>
<div class="leftMenu">
    @{
        if (UserInfo.uid > 0)
        {
            if (UserInfo.type == 1)
            {
                <div class="item">
                    <div class="header">组织管理</div>
                    <div class="menu">
                        <a class="item" href="@Url.Action("Index", "ORG")">组织列表</a>
                    </div>
                </div>
            }

            <div class="item">
                <div class="header">成员管理</div>
                <div class="menu">
                    <a class="item" href="@Url.Action("Index", "User")">成员列表</a>
                    <a class="item" href="@Url.Action("Index", "Record")">礼包分配记录</a>
                    @if (UserInfo.type != 3)
                    {
                        <a class="item" href="@Url.Action("Index", "Reward")">人员奖惩</a>
                    }
                </div>
            </div>
            <div class="item">
                <div class="header">系统管理</div>
                <div class="menu">
                    <a class="item" href="@Url.Action("Logout", "Login")">退出系统</a>
                </div>
            </div>
        }
    }
</div>

org.Admin/Views/Shared/_Page.cshtml
@model IPagedList
@using Webdiyer.WebControls.Mvc;

@Html.Pager(Model, new PagerOptions
{
	PageIndexParameterName = "p",
	FirstPageText = "«",
	LastPageText = "»",
	NextPageText = "›",
	PrevPageText = "‹",
	ContainerTagName = "ul",
	CssClass = "pagination pagination-outline",
	CurrentPagerItemTemplate = "<li class=\"page-number active\"><a href=\"#\">{0}</a></li>",
	DisabledPagerItemTemplate = "<li class=\"page-number\"><a>{0}</a></li>",
	PagerItemTemplate = "<li>{0}</li>"
})